services:
  - type: web
    name: health-copilot-backend
    env: node
    plan: free
    buildCommand: "npm install"
    startCommand: "node server/index.js"
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: PORT
        value: 3001
      - key: OPENAI_API_KEY
        sync: false
    healthCheckPath: /api/health

staticSites:
  - name: health-copilot-frontend
    buildCommand: "npm install && npm run build"
    publishPath: dist
    envVars:
      - key: VITE_API_BASE_URL
        fromService:
          type: web
          name: health-copilot-backend
          property: host

